apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opik.name" . }}-backend
  labels:
    {{- include "opik.labels" $  | nindent 4 }}
data:
  {{- range $key, $value := .Values.component.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}