openapi: 3.1.0
info :
  description : "APIs"
  version : "1.0.0"
  title : "APIs"
  contact :
    name : "Support"
    email : "support@comet.com"
  license :
    name : "Apache 2.0"
    url : "http://www.apache.org/licenses/LICENSE-2.0.html"

servers :
  - url : "{basePath}/{apiVersion}"
    description : "Local server"
    variables:
      basePath:
        default: "http://localhost:8080"
      apiVersion:
        default: "v1"